import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { searchTextbook, searchableSourceBlocks } from "@/lib/text-search";
import { learningUrl, textbookUrl } from "@/lib/textbook-links";
import { trialLessons } from "@/content/textbooks/bonjour-francais-1/trial-lessons";
import { directoryNodes } from "@/content/textbooks/bonjour-francais-1/directory";

const blockLabels:Record<string,string>={page_heading:"目录 / 标题",learning_objectives:"学习目标",dialogue:"对话",notes:"注释",vocabulary:"词汇",discovery:"初识",grammar:"语法",expressions:"重点表达",exercises:"练习",speaking:"交际",pronunciation:"发音",culture:"文化"};
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string}>}){const {q=""}=await searchParams;const results=searchTextbook(q);const trialIds=new Set(trialLessons.map(l=>l.id));const pages=new Set(searchableSourceBlocks.filter(b=>!b.id.startsWith("directory-")).map(b=>b.pdfPageIndex));return <AppShell active="/search"><div className="page search-page"><div className="page-title"><div><p className="eyebrow">TEXTBOOK SEARCH</p><h1>教材原文检索</h1><p>搜索法语、中文、短语、句子、语法、练习、Lesson 或教材页码。</p></div></div><section className="search-coverage"><strong>当前教材索引仅覆盖已完成核对的章节，并非整本教材。</strong><div><span><b>2</b> 已索引 Lesson</span><span><b>{pages.size}</b> 已索引页面</span><span><b>{searchableSourceBlocks.length}</b> 已核对内容块</span><span><b>2026-07-20</b> 最近更新</span></div><p>覆盖范围：完整教材目录、Unité 0 目录节点、Unité 1、Leçon 1 Bienvenue !、Leçon 2 Qui est-ce ?</p></section><form className="global-search" action="/search"><input name="q" defaultValue={q} placeholder="例如：être、自我介绍、Je m’appelle、教材第 24 页" autoFocus/><button type="submit">搜索教材</button></form>{q&&<div className="search-summary">“{q}” · {results.length} 条已核对结果</div>}<section className="search-results">{results.map(result=>{const isTrial=result.lessonId&&trialIds.has(result.lessonId);const unit=result.lessonId?directoryNodes.find(n=>n.id==="unit-1"):null;return <article key={result.id}><div className="result-meta"><span>{blockLabels[result.blockType]??result.blockType}</span><span>《你好！法语 1》</span><span>{unit?.titleFr??"教材目录"}</span>{result.printedPageNumber&&<span>教材第 {result.printedPageNumber} 页</span>}</div><h2>{result.originalText.slice(0,160)}{result.originalText.length>160?"…":""}</h2><p>内容块：{result.id} · {result.verificationStatus}</p><div>{isTrial&&<Link href={learningUrl({lessonId:result.lessonId!,sectionId:result.sectionId??undefined,sourceBlockId:result.id})}>在学习模式中查看</Link>}{isTrial?<Link href={textbookUrl({lessonId:result.lessonId!,pdfPageIndex:result.pdfPageIndex,sourceBlockId:result.id})}>定位教材原文</Link>:<Link href="/courses">在教材目录中查看</Link>}</div></article>})}{q&&results.length===0&&<div className="search-empty"><strong>未在已核对内容中找到结果</strong><p>该内容可能位于尚未完成索引的教材章节中。</p></div>}</section></div></AppShell>}
