"use client";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Icon } from "@/components/icons";
import { vocabulary } from "@/lib/mock-data";

export default function VocabularyPage(){ const [query,setQuery]=useState(""); const [favorites,setFavorites]=useState(false); const words=useMemo(()=>vocabulary.filter(v=>(!favorites||v.favorite)&&(v.french.toLowerCase().includes(query.toLowerCase())||v.chinese.includes(query))),[query,favorites]); return <AppShell active="/vocabulary"><div className="page">
  <div className="page-title"><div><p className="eyebrow">VOCABULARY</p><h1>单词本</h1><p>所有单词都保留教材出处，并按记忆状态安排复习。</p></div><button className="primary-button"><Icon name="cards"/> 开始闪卡复习 <span>16</span></button></div>
  <section className="vocab-stats"><div><small>全部单词</small><strong>186</strong><span>来自 4 Lessons</span></div><div><small>今日待复习</small><strong className="orange">16</strong><span>建议约 12 分钟</span></div><div><small>已掌握</small><strong className="green-text">124</strong><span>掌握度 ≥ 4</span></div><div><small>收藏</small><strong>28</strong><span>重点词汇</span></div></section>
  <div className="toolbar"><label className="search-box"><Icon name="search"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索法语或中文释义"/></label><select aria-label="筛选课程"><option>全部 Lessons</option><option>Lesson 1</option><option>Lesson 2</option></select><select aria-label="筛选掌握程度"><option>全部掌握程度</option><option>需要复习</option><option>已掌握</option></select><button onClick={()=>setFavorites(!favorites)} className={favorites?"selected":""}><Icon name="star"/> 仅收藏</button></div>
  <section className="word-table"><header><span>单词</span><span>释义</span><span>教材来源</span><span>掌握程度</span><span>下次复习</span><span/></header>{words.map(word=><article key={word.id}><div className="word-main"><button aria-label="播放发音"><Icon name="sound"/></button><div><strong>{word.french}</strong><small>{word.ipa} {word.gender && `· ${word.gender}`}</small></div></div><div><strong>{word.chinese}</strong><small>{word.partOfSpeech}{word.plural&&` · pl. ${word.plural}`}</small></div><div><span>Lesson {word.lessonId.replace("lesson-","")}</span><small>{word.source}</small></div><div><div className="mastery">{[1,2,3,4,5].map(n=><i key={n} className={n<=word.mastery?"filled":""}/>)}</div><small>{word.mastery>=4?"熟悉":word.mastery>=2?"学习中":"需加强"}</small></div><div><strong>{word.nextReview}</strong><small>{word.lastReviewed?`上次：${word.lastReviewed}`:"尚未复习"}</small></div><button className="star-button" aria-label="收藏"><Icon name="star"/></button></article>)}{words.length===0&&<div className="empty">没有找到匹配的单词</div>}</section>
</div></AppShell>}
