import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { Heatmap } from "@/components/heatmap";
import { Icon } from "@/components/icons";
import { ProgressRing } from "@/components/progress-ring";
import { currentLesson, mistakes } from "@/lib/mock-data";

export default function Dashboard() {
  return <AppShell active="/"><div className="page dashboard">
    <section className="welcome"><div><p className="eyebrow">MARDI, 15 JUILLET</p><h1>Bonjour, 哲 <span>👋</span></h1><p>今天继续前进一点点。你的法语学习已连续 <b>12 天</b>。</p></div><div className="daily-goal"><ProgressRing value={68} size={72}/><div><small>今日目标</small><strong>34 / 50 分钟</strong></div></div></section>
    <section className="hero-card"><div className="hero-copy"><span className="pill blue">继续学习</span><p className="lesson-index">A1 · LEÇON {currentLesson.number}</p><h2>{currentLesson.title}</h2><h3>{currentLesson.subtitle}</h3><p>今天学习自我介绍、国籍表达和动词 être 的基础用法。</p><div className="hero-meta"><span><Icon name="clock"/> 约 28 分钟</span><span>7 个学习环节</span></div><Link href={`/courses/${currentLesson.id}`} className="primary-button">继续本课 <Icon name="play"/></Link></div><div className="hero-visual"><span>Je m’appelle</span><strong>Sophie.</strong><small>Enchantée !</small><div className="floating-word one">Bonjour</div><div className="floating-word two">être</div></div></section>
    <section className="metrics-grid"><article><div className="metric-icon green"><Icon name="flame"/></div><div><small>连续学习</small><strong>12 <em>天</em></strong><span>个人最佳 18 天</span></div></article><article><div className="metric-icon blue"><Icon name="clock"/></div><div><small>本周学习</small><strong>4.6 <em>小时</em></strong><span className="up">↑ 18% 较上周</span></div></article><article><div className="metric-icon purple"><Icon name="words"/></div><div><small>已掌握词汇</small><strong>186 <em>个</em></strong><span>本周新增 24 个</span></div></article><article><div className="metric-icon amber"><Icon name="target"/></div><div><small>课程进度</small><strong>18<em>%</em></strong><span>2 / 12 Lessons</span></div></article></section>
    <div className="dashboard-columns"><section><div className="section-heading"><div><p className="eyebrow">TODAY</p><h2>今日任务</h2></div><span>3 / 5 完成</span></div><div className="task-list">{[[true,"完成 Lesson 1 复习","8 分钟"],[true,"复习 16 个单词","12 分钟"],[true,"听力跟读练习","10 分钟"],[false,"学习 être 的变位","15 分钟"],[false,"完成 Lesson 2 练习","12 分钟"]].map(([done,label,time])=><div className={done ? "done" : ""} key={String(label)}><button aria-label="切换完成状态"><Icon name={done ? "check" : ""}/></button><span>{label}</span><small>{time}</small></div>)}</div></section>
    <aside><div className="section-heading"><div><p className="eyebrow">REVIEW</p><h2>今日复习</h2></div><Link href="/vocabulary">查看全部</Link></div><div className="review-card"><div className="review-number"><strong>16</strong><span>待复习单词</span></div><div className="review-breakdown"><span><i className="dot red"/>4 个即将遗忘</span><span><i className="dot amber"/>12 个按计划复习</span></div><Link href="/vocabulary?mode=flashcard" className="secondary-button"><Icon name="cards"/> 开始闪卡复习</Link></div></aside></div>
    <div className="dashboard-columns lower"><section><div className="section-heading"><div><p className="eyebrow">ACTIVITY</p><h2>学习记录</h2></div><span>过去 12 周</span></div><div className="activity-card"><Heatmap/><div className="heatmap-legend"><span>少</span>{[0,1,2,3,4].map(n=><i key={n} data-level={n}/>)}<span>多</span></div></div></section><aside><div className="section-heading"><div><p className="eyebrow">MISTAKES</p><h2>最近错题</h2></div><Link href="/mistakes">错题本</Link></div><div className="mistake-preview">{mistakes.slice(0,2).map(m=><Link key={m.id} href="/mistakes"><span>{m.category}</span><p>{m.prompt}</p><small>错误 {m.errorCount} 次 · {m.lastError}</small></Link>)}</div></aside></div>
  </div></AppShell>;
}
