import Link from "next/link";
import { sourceBlocks, type TrialLesson } from "@/content/textbooks/bonjour-francais-1/trial-lessons";
import { learningUrl, textbookUrl } from "@/lib/textbook-links";
import { TextbookReader } from "./textbook-reader";
import { LessonPositionButton } from "./lesson-position-button";

export function LessonView({lesson,mode,pdfPageIndex,sourceBlockId}:{lesson:TrialLesson;mode:string;pdfPageIndex:number;sourceBlockId?:string}){
  const blocks=sourceBlocks.filter(block=>block.lessonId===lesson.id);
  const focusedBlock=sourceBlockId?sourceBlocks.find(block=>block.id===sourceBlockId):undefined;
  return <><div className="lesson-mode-tabs"><Link className={mode!=="textbook"?"active":""} href={learningUrl({lessonId:lesson.id,sourceBlockId})}>学习模式</Link><Link className={mode==="textbook"?"active":""} href={textbookUrl({lessonId:lesson.id,pdfPageIndex,sourceBlockId})}>教材模式</Link><span>教材第 {lesson.startPrintedPageNumber}–{lesson.endPrintedPageNumber} 页 · PDF 第 {lesson.startPdfPageIndex+1}–{lesson.endPdfPageIndex+1} 页</span></div>{mode==="textbook"?<TextbookReader lessonId={lesson.id} pdfPageIndex={pdfPageIndex} min={lesson.startPdfPageIndex} max={lesson.endPdfPageIndex} sourceBbox={focusedBlock?.sourceBbox}/>:<div className="grounded-sections">{lesson.sections.map(section=>{const sectionBlocks=blocks.filter(block=>section.sourceBlockIds.includes(block.id)); return <section id={section.id} key={section.id} className={`content-card grounded-section ${sourceBlockId&&section.sourceBlockIds.includes(sourceBlockId)?"source-highlight":""}`}><header><div><small>{section.titleFr}</small><h2>{section.titleZh}</h2></div><div className="section-source-actions"><LessonPositionButton lessonId={lesson.id} sectionId={section.id} sourceBlockId={sectionBlocks[0]?.id ?? section.id}/><Link href={textbookUrl({lessonId:lesson.id,pdfPageIndex:sectionBlocks[0]?.pdfPageIndex??lesson.startPdfPageIndex,sourceBlockId:sectionBlocks[0]?.id})}>查看教材原文 ↗</Link></div></header>{sectionBlocks.map(block=><article id={block.id} key={block.id} className={sourceBlockId===block.id?"source-highlight":""}><p>{block.originalText}</p><footer><span>教材第 {block.printedPageNumber} 页 · PDF 第 {block.pdfPageIndex+1} 页</span><span>{block.extractionMethod} · {block.verificationStatus}</span></footer></article>)}</section>})}</div>}</>;
}
