"use client";

import Link from "next/link";
import { useState } from "react";
import { learningCatalog } from "@/lib/learning/catalog";
import { useLearningStore } from "@/lib/learning/store";

export function MistakesClient() {
  const { hydrated, loading, state, recordExerciseResult } = useLearningStore();
  const [answers, setAnswers] = useState<Record<string, string>>({});
  if (!hydrated || !state) return <div className="learning-loading">正在读取错题记录…</div>;
  const mistakes = Object.values(state.mistakes);
  return <><div className="local-data-notice"><strong>掌握规则</strong><span>答错后进入错题本；重新练习连续答对 2 次后标记为已掌握。</span></div>{mistakes.length === 0 && <div className="search-empty"><strong>尚无错题</strong><p>可以先对已核对的教材练习进行自评，不会由系统虚构标准答案。</p></div>}<div className="mistake-list">{mistakes.map((mistake) => { const exercise = learningCatalog.exercises.find((item) => item.id === mistake.exerciseId); return <article className="content-card" key={mistake.exerciseId}><small>{mistake.lessonId.toUpperCase()} · {mistake.status === "mastered" ? "已掌握" : "待复习"}</small><h2>{exercise?.title ?? mistake.exerciseId}</h2><p>错误 {mistake.wrongCount} 次 · 连续答对 {mistake.consecutiveCorrectCount}/2 · {mistake.nextReviewAt ? `下次复习 ${mistake.nextReviewAt.slice(0,10)}` : "已解决"}</p><div className="review-actions"><button disabled={loading} onClick={() => void recordExerciseResult(mistake.exerciseId, mistake.lessonId, "self-assessed-wrong", false)}>答错</button><button disabled={loading} onClick={() => void recordExerciseResult(mistake.exerciseId, mistake.lessonId, "self-assessed-correct", true)}>答对</button><Link href={`/courses/${mistake.lessonId}?sourceBlockId=${mistake.exerciseId}`}>重新练习</Link></div></article>; })}</div><section className="practice-section"><h2>教材练习</h2><p>可判定的封闭题支持提交答案；听力、图片和开放题不虚构答案，只支持手动标记完成。</p><div className="mistake-list">{learningCatalog.exercises.map((exercise) => <article className="content-card" key={exercise.id}><small>{exercise.lessonId.toUpperCase()} · {exercise.exerciseType}</small><p>{exercise.title}</p>{exercise.evaluationMode === "automatic" ? <div className="answer-form"><input aria-label={`${exercise.id} 答案`} value={answers[exercise.id] ?? ""} placeholder="按题目顺序输入，用逗号分隔" onChange={(event) => setAnswers((current) => ({ ...current, [exercise.id]: event.target.value }))}/><button disabled={loading || !answers[exercise.id]?.trim()} onClick={() => { const answer = (answers[exercise.id] ?? "").toLowerCase().replace(/\s+/g, ""); const correct = exercise.acceptedAnswers.some((accepted) => accepted.toLowerCase().replace(/\s+/g, "") === answer); void recordExerciseResult(exercise.id, exercise.lessonId, answer, correct); }}>提交答案</button></div> : <div className="review-actions"><button disabled={loading} onClick={() => void recordExerciseResult(exercise.id, exercise.lessonId, "manual-completed", true)}>手动标记完成</button><Link href={`/courses/${exercise.lessonId}?sourceBlockId=${exercise.sourceBlockId}`}>打开教材材料</Link></div>}</article>)}</div></section></>;
}
