export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      textbooks: { Row: { id:string; title:string; level:string; edition:string|null; source_type:string; source_file_name:string|null; page_count:number|null; import_status:string; checksum:string|null; is_primary:boolean; metadata:Json; created_at:string; updated_at:string }; Insert: Partial<Database["public"]["Tables"]["textbooks"]["Row"]> & Pick<Database["public"]["Tables"]["textbooks"]["Row"],"title"|"level">; Update: Partial<Database["public"]["Tables"]["textbooks"]["Row"]> };
      chapters: { Row: { id:string; textbook_id:string; title:string; level:string; position:number; source_page_start:number|null; source_page_end:number|null; created_at:string }; Insert: Omit<Database["public"]["Tables"]["chapters"]["Row"],"id"|"created_at">; Update: Partial<Database["public"]["Tables"]["chapters"]["Row"]> };
      lessons: { Row: { id:string; chapter_id:string; slug:string; number:number; title:string; subtitle:string|null; objectives:string[]; estimated_minutes:number; source_page_start:number|null; source_page_end:number|null; source_revision:number; published_at:string|null; created_at:string; updated_at:string }; Insert: Partial<Database["public"]["Tables"]["lessons"]["Row"]> & Pick<Database["public"]["Tables"]["lessons"]["Row"],"chapter_id"|"slug"|"number"|"title">; Update: Partial<Database["public"]["Tables"]["lessons"]["Row"]> };
      lesson_sections: { Row: { id:string; lesson_id:string; kind:string; title:string; content:Json; position:number; estimated_minutes:number; source_page_start:number|null; source_page_end:number|null; created_at:string; updated_at:string }; Insert: Partial<Database["public"]["Tables"]["lesson_sections"]["Row"]> & Pick<Database["public"]["Tables"]["lesson_sections"]["Row"],"lesson_id"|"kind"|"title"|"position">; Update: Partial<Database["public"]["Tables"]["lesson_sections"]["Row"]> };
      vocabulary: { Row: { id:string; lesson_id:string; section_id:string|null; french:string; chinese:string; part_of_speech:string|null; gender:string|null; plural:string|null; ipa:string|null; audio_url:string|null; source_page:number|null; position:number; created_at:string }; Insert: Partial<Database["public"]["Tables"]["vocabulary"]["Row"]> & Pick<Database["public"]["Tables"]["vocabulary"]["Row"],"lesson_id"|"french"|"chinese">; Update: Partial<Database["public"]["Tables"]["vocabulary"]["Row"]> };
      vocabulary_progress: { Row: { id:string; user_id:string; vocabulary_id:string; mastery:number; is_favorite:boolean; review_count:number; ease_factor:number; interval_days:number; last_reviewed_at:string|null; next_review_at:string|null; updated_at:string }; Insert: Partial<Database["public"]["Tables"]["vocabulary_progress"]["Row"]> & Pick<Database["public"]["Tables"]["vocabulary_progress"]["Row"],"user_id"|"vocabulary_id">; Update: Partial<Database["public"]["Tables"]["vocabulary_progress"]["Row"]> };
      lesson_progress: { Row: { id:string; user_id:string; lesson_id:string; status:string; progress_percent:number; active_seconds:number; last_section_id:string|null; started_at:string|null; completed_at:string|null; updated_at:string }; Insert: Partial<Database["public"]["Tables"]["lesson_progress"]["Row"]> & Pick<Database["public"]["Tables"]["lesson_progress"]["Row"],"user_id"|"lesson_id">; Update: Partial<Database["public"]["Tables"]["lesson_progress"]["Row"]> };
      mistakes: { Row: { id:string; user_id:string; exercise_id:string; lesson_id:string; user_answer:Json; error_count:number; first_error_at:string; last_error_at:string; remastered_at:string|null }; Insert: Partial<Database["public"]["Tables"]["mistakes"]["Row"]> & Pick<Database["public"]["Tables"]["mistakes"]["Row"],"user_id"|"exercise_id"|"lesson_id"|"user_answer">; Update: Partial<Database["public"]["Tables"]["mistakes"]["Row"]> };
      daily_plans: { Row: { id:string; user_id:string; plan_date:string; tasks:Json; target_minutes:number; completed_minutes:number; created_at:string; updated_at:string }; Insert: Partial<Database["public"]["Tables"]["daily_plans"]["Row"]> & Pick<Database["public"]["Tables"]["daily_plans"]["Row"],"user_id"|"plan_date">; Update: Partial<Database["public"]["Tables"]["daily_plans"]["Row"]> };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: { lesson_status:"locked"|"available"|"in_progress"|"completed"; review_rating:"again"|"hard"|"good"|"easy" };
    CompositeTypes: Record<string, never>;
  };
};
